---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-cluster-config
data:
  rocketmq-broker-0.conf: |
    brokerClusterName = KingdeeRocketMQCluster
    brokerName = broker0
    brokerId = 0
    brokerIP1 = 10.9.18.191
    brokerRole=SYSC_MASTER
    flushDiskType=ASYNC_FLUSH
  rocketmq-broker-1.conf: |
    brokerClusterName = KingdeeRocketMQCluster
    brokerName = broker1
    brokerId = 0
    brokerIP1 = 10.9.18.191
    brokerRole=SYSC_MASTER
    flushDiskType=ASYNC_FLUSH
  rocketmq-broker-2.conf: |
    brokerClusterName = KingdeeRocketMQCluster
    brokerName = broker0
    brokerId = 1
    brokerIP1 = 10.9.18.191
    brokerRole=SLAVE
    flushDiskType=ASYNC_FLUSH
  rocketmq-broker-3.conf: |
    brokerClusterName = KingdeeRocketMQCluster
    brokerName = broker1
    brokerId = 1
    brokerIP1 = 10.9.18.191
    brokerRole=SLAVE
    flushDiskType=ASYNC_FLUSH
---
apiVersion: v1
kind: Service
metadata:
  name: $CI_PROJECT_PATH_SLUG-broker-headless
  labels:
    app: $CI_PROJECT_PATH_SLUG-broker
spec:
  clusterIP: None
  selector:
    app: $CI_PROJECT_PATH_SLUG-broker
---
apiVersion: v1
kind: Service
metadata:
  name: $CI_PROJECT_PATH_SLUG-broker
spec:
  externalIPs: $EXTERNAL_IPS
  ports:
    - name: rocketmq-cluster-broker-10909
      port: 10909
    - name: rocketmq-cluster-broker-10911
      port: 10911
    - name: rocketmq-cluster-broker-10912
      port: 10912
  selector:
    app: $CI_PROJECT_PATH_SLUG-broker
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: rocketmq-broker
  annotations:
    app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
    app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
  labels:
    app: $CI_PROJECT_PATH_SLUG-broker
spec:
  serviceName: $CI_PROJECT_PATH_SLUG-broker-headless
  replicas: 1
  selector:
    matchLabels:
      app: $CI_PROJECT_PATH_SLUG-broker
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage-kingdee-services-rocketmq-cluster
        resources:
          requests:  
            storage: 20Gi
  template:
    metadata:
      annotations:
        app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
        app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
      labels:
        app: $CI_PROJECT_PATH_SLUG-broker
    spec:
      volumes:
      - name: config
        configMap:
          name: rocketmq-cluster-config
      containers:
      - name: broker
        image: apacherocketmq/rocketmq-broker:4.5.0-alpine
        imagePullPolicy: IfNotPresent
        env:
          - name: JAVA_OPT_EXT
            value: $BROKER_JAVA_OPT_EXT
        volumeMounts:
          - name: config
            mountPath: /home/rocketmq/config
          - name: data
            mountPath: /home/rocketmq/logs
            subPath: logs
          - name: data
            mountPath: /home/rocketmq/store
            subPath: store
        lifecycle:
          postStart:
            exec:
              command: ["sh","-c", "cp /home/rocketmq/config/$(hostname -s).conf /root/rocketmq-4.5.0/bin/broker.conf"]
        command: ["sh","mqbroker", "-n", "rocketmq-cluster-namesrv:9876", "-c", "broker.conf"]
      
