---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rocketmq-cluster-namesrv
  annotations:
    app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
    app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
  labels:
    app: $CI_PROJECT_PATH_SLUG-namesrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $CI_PROJECT_PATH_SLUG-namesrv
  template:
    metadata:
      annotations:
        app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
        app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
      labels:
        app: $CI_PROJECT_PATH_SLUG-namesrv
    spec:
      containers:
      - name: namesrv
        image: apacherocketmq/rocketmq-nameserver:4.5.0-alpine
        imagePullPolicy: IfNotPresent
        command: ["sh"]
        args: ["mqnamesrv"]

---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-cluster-namesrv
spec:
  clusterIP: 10.43.186.169
  externalIPs: $EXTERNAL_IPS
  ports:
    - name: rocketmq-cluster-namesrv-9876
      port: 9876
  selector:
    app: $CI_PROJECT_PATH_SLUG-namesrv
